services:
  backend:
    container_name: helperwecare_backend
    build:
      context: .  # Use the current directory as the context
      dockerfile: my-node-backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Optional: for hot-reloading during development
    environment:
      - MONGO_URI=mongodb://mongodb:27017/studentsdb  # Adjust based on your MongoDB setup
    networks:
    - helperwecare_network

  frontend:
    container_name: helperwecare_web
    build:
      context: .  # Use the current directory as the context
      dockerfile: app-angular-frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend  # Ensure backend is started before frontend
    networks:
    - helperwecare_network

volumes:
  mongodb_data:

networks:
  helperwecare_network:
    external: true